### ISSUE TITLE
support 27.0.1; play services 11.6.0

### ISSUE THREAD

**Issue by kvolkers** [Notificare/notificare-mvn-repo#6]
Please update:
support 27.0.1
play services 11.6.0

Thanks!

**Comment by silentjohnny** [comment]
These updates will be done in the next update, which is still undergoing some testing.

**Comment by kvolkers** [comment]
Hi @silentjohnny do you have an approx. release date to share?

Notificare is currently the last dependency preventing me from updating, which would fix a critical issue.

**Comment by silentjohnny** [comment]
Hi @kvolkers,

We can not assume everybody is already building against Android SDK 27, so we are testing this thoroughly before releasing. However, since there should be no compatibility issues in the Support Libraries between 26 and 27, you can already go ahead and manually override the transitive dependencies in our AAR.

Just use something like this in your build.gradle and you should be good to go until we release an AAR that was built against SDK 27:

```
dependencies {

    compile group: 're.notifica', name: 'notificare-push-lib-android', version: '1.11.0', ext: 'aar', transitive: false
    compile group: 'com.google.http-client', name: 'google-http-client-jackson2', version: '1.22.0'
    compile group: 'com.google.oauth-client', name: 'google-oauth-client', version: '1.22.0'
    compile 'com.google.android.gms:play-services-location:11.6.0'
    compile 'com.google.android.gms:play-services-maps:11.6.0'
    compile 'com.google.android.gms:play-services-gcm:11.6.0'
    compile 'com.google.firebase:firebase-messaging:11.6.0'
    compile 'com.android.support:appcompat-v7:27.0.1'
    compile 'com.android.support:palette-v7:27.0.1'
    compile 'com.android.support:design:27.0.1'
    compile 'com.android.support:exifinterface:27.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'

}
```

Release of the Notificare SDK is planned for this month, so after this is updated, you can go back to using normal transitive dependency.
